[FRONT] Récupération des info global du marché
MirakuSan/infresCoinMarketCap pull request #38
Opened 2021-09-26 19:29 UTC by MirakuSan

closes #20

2021-09-26 20:32 UTC, Toxiqh requested changes
Quelques petites coquilles de syntaxe mais sinon - OK

2021-09-26 20:32 UTC, Toxiqh commented on client/public/index.html
>      <meta
A mettre en une seule ligne

2021-09-26 20:32 UTC, Toxiqh commented on client/public/index.html
> +<noscript>You need to enable JavaScript to run this app.</noscript>
Manque indentation

2021-09-26 20:32 UTC, Toxiqh commented on client/public/index.html
> +<div id="root"></div>
Manque indentation

2021-09-26 20:32 UTC, Toxiqh commented on client/src/App.js
> +import AppAppBar from "./view/AppAppBar";
```suggestion
import AppAppBar from './view/AppAppBar';
```

2021-09-26 20:32 UTC, Toxiqh commented on client/src/App.js
> +import AppFooter from "./view/AppFooter";
```suggestion
import AppFooter from './view/AppFooter';
```

2021-09-26 20:32 UTC, Toxiqh commented on client/src/App.js
> +import withRoot from "./withRoot";
```suggestion
import withRoot from './withRoot';
```

2021-09-26 20:32 UTC, Toxiqh commented on client/src/App.js
> +import Global from "./components/Global";
```suggestion
import Global from './components/Global';
```

2021-09-26 20:32 UTC, Toxiqh commented on client/src/components/Global.js
> +                console.log(results);
```suggestion

```

2021-09-26 20:32 UTC, Toxiqh commented on client/src/components/AppBar.js
> +    return <MuiAppBar elevation={0} position="fixed" {...props} />;
```suggestion
    return <MuiAppBar elevation={0} position='fixed' {...props} />;
```

2021-09-26 20:32 UTC, Toxiqh commented on client/src/components/Global.js
> +                            <Typography variant="body2" sx={{my: 2}}>
```suggestion
                            <Typography variant='body2' sx={{my: 2}}>
```

2021-09-26 20:32 UTC, Toxiqh commented on client/src/components/Global.js
> +                            <Typography variant="body2" sx={{my: 2}}>
```suggestion
                            <Typography variant='body2' sx={{my: 2}}>
```

2021-09-26 20:32 UTC, Toxiqh commented on client/src/components/Global.js
> +                            <Typography variant="body2" sx={{my: 2}}>
```suggestion
                            <Typography variant='body2' sx={{my: 2}}>
```

2021-09-26 20:32 UTC, Toxiqh commented on client/src/components/Global.js
> +                            <Typography variant="body2" sx={{my: 2}}>
```suggestion
                            <Typography variant='body2' sx={{my: 2}}>
```

2021-09-26 20:32 UTC, Toxiqh commented on client/src/view/AppAppBar.js
> +import {Box} from "@mui/material";
```suggestion
import {Box} from '@mui/material';
```

2021-09-26 20:32 UTC, Toxiqh commented on client/src/view/AppAppBar.js
> +            <AppBar position="fixed">
```suggestion
            <AppBar position='fixed'>
```

2021-09-26 20:32 UTC, Toxiqh commented on client/src/view/AppAppBar.js
> +                        variant="h6"
```suggestion
                        variant='h6'
```

2021-09-26 20:32 UTC, Toxiqh commented on client/src/view/AppAppBar.js
> +                        underline="none"
```suggestion
                        underline='none'
```

2021-09-26 20:32 UTC, Toxiqh commented on client/src/view/AppAppBar.js
> +                        color="inherit"
```suggestion
                        color='inherit'
```

2021-09-26 20:32 UTC, Toxiqh commented on client/src/view/AppAppBar.js
> +                        href="/"
```suggestion
                        href='/'
```

2021-09-26 20:32 UTC, Toxiqh commented on client/src/view/AppFooter.js
> +                        direction="column"
```suggestion
                        direction='column'
```

2021-09-26 20:32 UTC, Toxiqh commented on client/src/view/AppFooter.js
> +                        justifyContent="flex-end"
```suggestion
                        justifyContent='flex-end'
```

2021-09-27 06:37 UTC, MirakuSan commented on client/public/index.html
> +<noscript>You need to enable JavaScript to run this app.</noscript>
vu ensemble pas possible

2021-09-27 06:41 UTC, MirakuSan commented on client/public/index.html
> +<div id="root"></div>
vu ensemble pas possible.

2021-09-27 06:55 UTC, Toxiqh approved these changes

2021-09-27 06:59 UTC, merged